services:
  - type: web
    name: mad-to-ride
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_USERNAME
        value: Madmax
      - key: ADMIN_PASSWORD
        value: Pa$$w0rd@Madmax
      - key: WHATSAPP_LINK
        value: https://chat.whatsapp.com/HbRgZJa1Rqm5Kbso36WDWf?mode=hqctcla
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000


